# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    access_denied_url: /login
    encoders:
        AppBundle\Entity\User: plaintext
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: name


    firewalls:
#        api:
#            pattern: ^/api/
#            provider: db_provider
#            http_basic: ~
        default:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PAGE_1, ROLE_PAGE_2]
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/page/1, roles: ROLE_PAGE_1 }
        - { path: ^/page/2, roles: ROLE_PAGE_2 }
